repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.1
  hooks:
    - id: ruff-check
      args: [ --fix ]
      files: ^app/|^tests/|^scripts/|^bottles_refund_system\.db$
    - id: ruff-format
      files: ^app/|^tests/|^scripts/|^bottles_refund_system\.db$