services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bottle-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["bash", "scripts/start.sh"]
